name: Build

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Update VERSION file
        run: git describe --tags | tr -d '\n' > VERSION

      - name: Install composer dependencies
        run: make install

      - name: Run syntax linter
        run: make sniff

#      - name: Run static analysis
#        run: make analyse

      - name: Run unit tests
        run: make test
